version: "2"
services:
    app:
        build: .
        environment:
            PORT: 8080
            REDIS_URL: redis://store:6379/
            CI: "true"
        command: npm start
        ports:
            - 8080:8080
        depends_on:
            - store
    store:
        image: redis:5.0.7-alpine
        ports:
            - 6379:6379
